name: dotsite
description: dotsite

version: 1.0.0+1

environment:
  sdk: ">=2.8.3 <3.0.0"

dependencies:
  camera:
    git:
      url: git@github.com:5hyn3/plugins.git
      path: packages/camera
      ref: modify-camera-plugin-to-enable-high-resolution-preview
  freezed_annotation:
  flutter_state_notifier:
  path_provider:
  vsync_provider:
  fluttertoast: ^4.0.0
  objectbox: ^0.6.4
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed:
  objectbox_generator: ^0.6.4
  flutter_launcher_icons:
  flutter_localizations:
    sdk: flutter

flutter_icons:
  image_path: "icon/icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
